spring:
  application:
    name: torneos
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://dpg-d8et8jho3t8c73fr92ng-a.oregon-postgres.render.com:5432/torneos_db_jdnq
    username: torneos_db_jdnq_user
    password: bEpj9KUxxwAXOF9WuJxtZ032n4561GwF
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

stripe:
  api-key: sk_test_51TlADyFXG1Xz5c0o0YqeQzFP24OGmTFtSgL7iCIr1iolgnodaj9YdKT8Gn4J8eyyKF38TkUYsTL6ldapGoJeJZOu00h4o9FiX7
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_placeholder}

server:
  port: 8080